project:
  type: website
  output-dir: docs

website:
  title: "ZI젼남규짱짱"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - homework1.qmd
      - homework2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



