project:
  type: website
  output-dir: docs

website:
  title: "ZI젼남규짱짱"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index_index.qmd
        text: hw & project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



